apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patroni-cluster.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "patroni-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  superuser-password: {{ .Values.postgresql.password | b64enc }}
  replication-password: {{ .Values.postgresql.replicationPassword | b64enc }}
