{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "patroni-cluster.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "patroni-cluster.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "patroni-cluster.fullname" . }}-cluster-role
  labels:
    {{- include "patroni-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "patroni-cluster.fullname" . }}-cluster-role-binding
  labels:
    {{- include "patroni-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "patroni-cluster.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "patroni-cluster.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
